In [16]:
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.layers import Embedding, LSTM, Dense
from tensorflow.keras.models import Sequential
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.optimizers import Adam
import pickle
import numpy as np
import os

In [5]:
file = open("Dataset/thepictureofdoriangray.txt", "r", encoding = "utf8")
lines = []
for i in file:
    lines.append(i)
    
data = ""
for i in lines:
  data = ' '. join(lines) 
 
data = data.replace('\n', '').replace('\r', '').replace('“','').replace('”','')

data = data.split()
data = ' '.join(data)
data[:500]

'The Project Gutenberg eBook of The Picture of Dorian Gray This ebook is for the use of anyone anywhere in the United States and most other parts of the world at no cost and with almost no restrictions whatsoever. You may copy it, give it away or re-use it under the terms of the Project Gutenberg License included with this ebook or online at www.gutenberg.org. If you are not located in the United States, you will have to check the laws of the country where you are located before using this eBook.'

In [17]:
tokenizer = Tokenizer()
tokenizer.fit_on_texts([data])
 
# saving the tokenizer to predict 
pickle.dump(tokenizer, open('token.pkl', 'wb'))
 
sequence_data = tokenizer.texts_to_sequences([data])[0]
sequence_data[:15]

[1, 131, 261, 651, 2, 1, 157, 2, 27, 63, 62, 651, 14, 18, 1]

In [18]:
vocab_size = len(tokenizer.word_index) + 1
print(vocab_size)
sequences = []
 
for i in range(3, len(sequence_data)):
    words = sequence_data[i-3:i+1]
    sequences.append(words)
     
print("The Length of sequences are: ", len(sequences))
sequences = np.array(sequences)
sequences[:10]

7464
The Length of sequences are:  82697


array([[  1, 131, 261, 651],
       [131, 261, 651,   2],
       [261, 651,   2,   1],
       [651,   2,   1, 157],
       [  2,   1, 157,   2],
       [  1, 157,   2,  27],
       [157,   2,  27,  63],
       [  2,  27,  63,  62],
       [ 27,  63,  62, 651],
       [ 63,  62, 651,  14]])

In [8]:
X = []
y = []
for i in sequences:
    X.append(i[0:3])
    y.append(i[3])
X = np.array(X)
y = np.array(y)
print("Data: ", X[:10])
print("Response: ", y[:10])
y = to_categorical(y, num_classes=vocab_size)
y[:5]

Data:  [[  1 131 261]
 [131 261 651]
 [261 651   2]
 [651   2   1]
 [  2   1 157]
 [  1 157   2]
 [157   2  27]
 [  2  27  63]
 [ 27  63  62]
 [ 63  62 651]]
Response:  [651   2   1 157   2  27  63  62 651  14]


array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.]], dtype=float32)

In [10]:
from tensorflow.keras.callbacks import ModelCheckpoint
 
checkpoint = ModelCheckpoint("next_words.h5", monitor='loss', verbose=1, save_best_only=True)
model.compile(loss="categorical_crossentropy", optimizer=Adam(learning_rate=0.001),metrics=['accuracy'])
model.fit(X, y, epochs=70, batch_size=64, callbacks=[checkpoint])

Epoch 1/70
1293/1293 [==============================] - ETA: 0s - loss: 6.4800
Epoch 1: loss improved from inf to 6.47999, saving model to next_words.h5


C:\Users\Harsh\AppData\Local\anaconda3\Lib\site-packages\keras\src\engine\training.py:3079: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(


1293/1293 [==============================] - 326s 249ms/step - loss: 6.4800
Epoch 2/70
1293/1293 [==============================] - ETA: 0s - loss: 5.9009
Epoch 2: loss improved from 6.47999 to 5.90091, saving model to next_words.h5
1293/1293 [==============================] - 326s 252ms/step - loss: 5.9009
Epoch 3/70
1293/1293 [==============================] - ETA: 0s - loss: 5.5262
Epoch 3: loss improved from 5.90091 to 5.52617, saving model to next_words.h5
1293/1293 [==============================] - 321s 248ms/step - loss: 5.5262
Epoch 4/70
1293/1293 [==============================] - ETA: 0s - loss: 5.2407
Epoch 4: loss improved from 5.52617 to 5.24068, saving model to next_words.h5
1293/1293 [==============================] - 318s 246ms/step - loss: 5.2407
Epoch 5/70
1293/1293 [==============================] - ETA: 0s - loss: 4.9991
Epoch 5: loss improved from 5.24068 to 4.99907, saving model to next_words.h5
1293/1293 [==============================] - 323s 250ms/step - loss:

1293/1293 [==============================] - 327s 253ms/step - loss: 0.5130
Epoch 37/70
1293/1293 [==============================] - ETA: 0s - loss: 0.5046
Epoch 37: loss improved from 0.51302 to 0.50457, saving model to next_words.h5
1293/1293 [==============================] - 324s 251ms/step - loss: 0.5046
Epoch 38/70
1293/1293 [==============================] - ETA: 0s - loss: 0.5012
Epoch 38: loss improved from 0.50457 to 0.50117, saving model to next_words.h5
1293/1293 [==============================] - 327s 253ms/step - loss: 0.5012
Epoch 39/70
1293/1293 [==============================] - ETA: 0s - loss: 0.4898
Epoch 39: loss improved from 0.50117 to 0.48976, saving model to next_words.h5
1293/1293 [==============================] - 325s 252ms/step - loss: 0.4898
Epoch 40/70
1293/1293 [==============================] - ETA: 0s - loss: 0.4773
Epoch 40: loss improved from 0.48976 to 0.47733, saving model to next_words.h5
1293/1293 [==============================] - 323s 250ms/step

In [15]:
from tensorflow.keras.models import load_model
 
model = load_model('next_words.h5')
tokenizer = pickle.load(open('token.pkl', 'rb'))
 
def Predict_Next_Words(model, tokenizer, text):
  seq = tokenizer.texts_to_sequences([text])
  seq = np.array(seq)
  preds = np.argmax(model.predict(seq))
  predicted_word = ""
   
  for key, value in tokenizer.word_index.items():
      if value == preds:
          predicted_word = key
          break
   
  print(predicted_word)

    
    
while(True):
    txt = input('Enter 3 words : ')
    if(txt=='exit'):
        break
    Predict_Next_Words(model, tokenizer, txt)


Enter 3 words : passed a dreadful
1/1 [==============================] - 1s 628ms/step
evening
Enter 3 words : I cannot mimic
1/1 [==============================] - 0s 23ms/step
one
Enter 3 words : exit


In [22]:
while(True):
    txt = input('Enter 3 words : ')
    if(txt=='exit'):
        break
    Predict_Next_Words(model, tokenizer, txt)

Enter 3 words : passed a dreadful
1/1 [==============================] - 1s 838ms/step
evening
Enter 3 words : I cannot mimic
1/1 [==============================] - 0s 92ms/step
one
Enter 3 words : exit


In [2]:
from tensorflow.keras.models import load_model
import pickle
model = load_model('next_words.h5')
tokenizer = pickle.load(open('token.pkl', 'rb'))